### ISSUE TITLE
[Design][Spec] Console.rest v3

### ISSUE THREAD

**Issue by JonathanMontane** [luckymarmot/console-rest#13]
We redesigned console.rest entirely to have a much simpler / cleaner design

![image](https://cloud.githubusercontent.com/assets/5136989/19185924/0c31bb40-8c84-11e6-93f2-a4579faa2075.png)
![image](https://cloud.githubusercontent.com/assets/5136989/19185940/1d54cb92-8c84-11e6-83e5-d72bfb419244.png)
![image](https://cloud.githubusercontent.com/assets/5136989/19185948/2628681e-8c84-11e6-931a-d7099289ca5a.png)

**Comment by mittsh** [comment]
Ok! Might be good to give it a go…
